### ISSUE TITLE
Invalid Path

### ISSUE THREAD

**Issue by Bit145** [myst33d/AudioServicePatch#1]
I get the following error by using the command given in readme:
`error: invalid path '/datadrive/Evolution-X/frameworks/base/services/core/java/com/android/server/audio/AudioService.java'`
But, it works if I replace the command with: 
`git apply --unsafe-paths --directory=(path to build directory)/frameworks/base (path to directory with a patch)/AudioService.patch`

**Comment by myst33d** [comment]
Oops, i ignored this issue :P 
What Android version were you compiling?

**Comment by Bit145** [comment]
I was compiling Evolution X pie

**Comment by myst33d** [comment]
Ok i added this command to a README.md. So probably this is not an issue now.
